# Generated by Django 5.1.7 on 2025-03-18 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Enseignant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('prenom', models.CharField(max_length=255)),
                ('role', models.CharField(choices=[('P', 'PROF'), ('A', 'ADMIN'), ('S', 'SUPER ADMIN')], max_length=255)),
                ('cin', models.CharField(max_length=255, unique=True)),
                ('photo_profil', models.FileField(upload_to='profil_prof/%Y/%m/%d/')),
            ],
        ),
    ]
