# Generated by Django 5.1.7 on 2025-03-22 13:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('educat', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Matiere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=15, unique=True)),
                ('niveau', models.CharField(choices=[('A1', 'A1 - Débutant'), ('A2', 'A2 - Élémentaire'), ('B1', 'B1 - Intermédiaire'), ('B2', 'B2 - Avancé'), ('C1', 'C1 - Expérimenté'), ('C2', 'C2 - Maîtrise')], max_length=2)),
                ('volume_horaire', models.IntegerField(help_text='Volume horaire total en heures')),
                ('enseignant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='educat.enseignant')),
            ],
        ),
    ]
