# Generated by Django 5.1.7 on 2025-03-22 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('educat', '0002_matiere'),
    ]

    operations = [
        migrations.CreateModel(
            name='Etudient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('prenom', models.CharField(max_length=255)),
                ('cin', models.CharField(max_length=255)),
                ('date_inscription', models.DateTimeField(auto_now_add=True)),
                ('photo_profil', models.FileField(upload_to='profil_prof/%Y/%m/%d/')),
            ],
        ),
        migrations.CreateModel(
            name='Groupe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('description', models.TextField()),
                ('max_insription', models.IntegerField(default=0, max_length=255)),
            ],
        ),
    ]
