# Generated by Django 5.1.7 on 2025-03-22 18:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('educat', '0003_etudient_groupe'),
    ]

    operations = [
        migrations.AddField(
            model_name='etudient',
            name='groupe',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='educat.groupe'),
        ),
    ]
