# Generated by Django 5.1.7 on 2025-03-22 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('educat', '0004_etudient_groupe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupe',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
