# Generated by Django 5.1.7 on 2025-03-23 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('educat', '0006_alter_etudient_photo_profil'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupe',
            name='name',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
