# Generated by Django 5.1.7 on 2025-03-23 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('educat', '0007_alter_groupe_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='groupe',
            old_name='max_insription',
            new_name='max_inscription',
        ),
    ]
