# Generated by Django 5.1.7 on 2025-03-24 21:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('educat', '0008_rename_max_insription_groupe_max_inscription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etudient',
            name='groupe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='educat.groupe'),
        ),
    ]
