# Generated by Django 5.1.7 on 2025-04-01 19:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('educat', '0009_alter_etudient_groupe'),
    ]

    operations = [
        migrations.AddField(
            model_name='matiere',
            name='groupes',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='educat.groupe'),
        ),
    ]
