# Generated by Django 5.1.7 on 2025-04-05 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('educat', '0010_matiere_groupes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupe',
            name='max_inscription',
            field=models.IntegerField(default=0),
        ),
        migrations.RemoveField(
            model_name='matiere',
            name='enseignant',
        ),
        migrations.RemoveField(
            model_name='matiere',
            name='groupes',
        ),
        migrations.AddField(
            model_name='matiere',
            name='enseignant',
            field=models.ManyToManyField(blank=True, to='educat.enseignant'),
        ),
        migrations.AddField(
            model_name='matiere',
            name='groupes',
            field=models.ManyToManyField(blank=True, to='educat.groupe'),
        ),
    ]
