# Generated by Django 5.1.7 on 2025-04-05 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('educat', '0011_alter_groupe_max_inscription_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='matiere',
            name='groupes',
        ),
        migrations.AddField(
            model_name='enseignant',
            name='groupes',
            field=models.ManyToManyField(blank=True, to='educat.groupe'),
        ),
    ]
