# Generated by Django 5.1.7 on 2025-04-06 15:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('educat', '0012_remove_matiere_groupes_enseignant_groupes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='enseignant',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='enseignant',
            name='photo_profil',
            field=models.FileField(blank=True, null=True, upload_to='profil_prof/%Y/%m/%d/'),
        ),
    ]
