# Generated by Django 5.1.7 on 2025-04-06 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('educat', '0013_enseignant_user_alter_enseignant_photo_profil'),
    ]

    operations = [
        migrations.AddField(
            model_name='enseignant',
            name='is_first_login',
            field=models.BooleanField(default=True),
        ),
    ]
