# Generated by Django 5.1.7 on 2025-04-06 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('educat', '0014_enseignant_is_first_login'),
    ]

    operations = [
        migrations.AddField(
            model_name='enseignant',
            name='temp_password',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
