# Generated by Django 5.1.7 on 2025-04-06 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('educat', '0016_remove_matiere_enseignant_matiere_enseignant'),
    ]

    operations = [
        migrations.AddField(
            model_name='etudient',
            name='niveau',
            field=models.CharField(choices=[('A1', 'A1 - Débutant'), ('A2', 'A2 - Élémentaire'), ('B1', 'B1 - Intermédiaire'), ('B2', 'B2 - Avancé'), ('C1', 'C1 - Expérimenté'), ('C2', 'C2 - Maîtrise')], default='A1', max_length=2),
        ),
    ]
